### ISSUE TITLE
Error Running App

### ISSUE THREAD

**Issue by LudensNoir** [gauravreddy08/food-vision#5]
After trying out the app with a couple images its suddenly stopped running and it keeps showing

![image (1)](https://github.com/gauravreddy08/food-vision/assets/126321380/7fcf9eeb-c612-4602-b0f6-843ddb7e1355)

**Comment by gauravreddy08** [comment]
This happens due to the Streamlit cloud's resource limit. I hope it works fine if you download the source code and host the website from your local machine.

Anyways I plan on migrating the app to HuggingFace Spaces in the near future. Let's see!!
